### ISSUE TITLE
Uncaught TypeError: editor.createFold is not a function

### ISSUE THREAD

**Issue by jbaayen** [modelica-tools/atom-language-modelica#36]
[Enter steps to reproduce:]

1. Load a Modelica file
2. Select "Toggle annotations"

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-modelica](https://github.com/modelica-tools/atom-language-modelica) package 0.5.1

### Stack Trace

Uncaught TypeError: editor.createFold is not a function

```
At /Users/jorn.baayen/.atom/packages/language-modelica/lib/modelica.coffee:64

TypeError: editor.createFold is not a function
    at Object.toggleallannotations (/packages/language-modelica/lib/modelica.coffee:64:12)
    at /packages/language-modelica/lib/modelica.coffee:15:106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:49.7.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  3x -2:47.7.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:50.4.0 window:toggle-full-screen (input.hidden-input)
  2x -1:13.8.0 core:backspace (input.hidden-input)
     -0:32 window:toggle-full-screen (input.hidden-input)
     -0:12.2.0 language-modelica:toggleallannotations (input.hidden-input)
```

### Non-Core Packages

```
language-antlr4 0.1.0 
language-cmake 0.3.0 
language-csv 1.1.2 
language-cython 0.3.0 
language-latex 1.0.0 
language-modelica 0.5.1 
language-restructuredtext 1.1.0 
```

**Comment by thorade** [comment]
Thanks for the report. I can reproduce the error, but I do not understand where it comes from. 
The annotation view was implemented by @tshort, maybe he understands the error message?
